/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemBolsa;

/**
 *
 * @author derp_
 */
public class Carteira extends javax.swing.JInternalFrame {

    /**
     * Creates new form Carteira
     */
    public Carteira() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnCarteira = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCarteira01 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCarteira02 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbCarteira03 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setTitle("Carteira");

        jpnCarteira.setBackground(new java.awt.Color(204, 204, 204));

        tbCarteira01.setForeground(new java.awt.Color(255, 255, 255));
        tbCarteira01.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ativo", "Quantidade", "Valor compra", "Valor atual", "Total Compra", "Total Atual", "Lucro/Prejuizo", "%"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCarteira01.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tbCarteira01);
        if (tbCarteira01.getColumnModel().getColumnCount() > 0) {
            tbCarteira01.getColumnModel().getColumn(0).setResizable(false);
            tbCarteira01.getColumnModel().getColumn(1).setResizable(false);
            tbCarteira01.getColumnModel().getColumn(2).setResizable(false);
            tbCarteira01.getColumnModel().getColumn(3).setResizable(false);
            tbCarteira01.getColumnModel().getColumn(4).setResizable(false);
            tbCarteira01.getColumnModel().getColumn(5).setResizable(false);
            tbCarteira01.getColumnModel().getColumn(6).setResizable(false);
            tbCarteira01.getColumnModel().getColumn(7).setResizable(false);
        }

        tbCarteira02.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"TOTAL DE ATIVOS", " ", null, null, null, null}
            },
            new String [] {
                "", "", "Total Compra", "Total Atual", "Lucro/Prejuizo", "%"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbCarteira02);
        if (tbCarteira02.getColumnModel().getColumnCount() > 0) {
            tbCarteira02.getColumnModel().getColumn(0).setResizable(false);
            tbCarteira02.getColumnModel().getColumn(1).setResizable(false);
            tbCarteira02.getColumnModel().getColumn(2).setResizable(false);
            tbCarteira02.getColumnModel().getColumn(3).setResizable(false);
            tbCarteira02.getColumnModel().getColumn(4).setResizable(false);
            tbCarteira02.getColumnModel().getColumn(5).setResizable(false);
        }

        tbCarteira03.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"CONTA CORRENTE", null, null, null, null, null}
            },
            new String [] {
                "", "", "Disponível", "Em carteira", "Saldo", "%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbCarteira03);
        if (tbCarteira03.getColumnModel().getColumnCount() > 0) {
            tbCarteira03.getColumnModel().getColumn(0).setResizable(false);
            tbCarteira03.getColumnModel().getColumn(1).setResizable(false);
            tbCarteira03.getColumnModel().getColumn(2).setResizable(false);
            tbCarteira03.getColumnModel().getColumn(3).setResizable(false);
            tbCarteira03.getColumnModel().getColumn(4).setResizable(false);
            tbCarteira03.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jpnCarteiraLayout = new javax.swing.GroupLayout(jpnCarteira);
        jpnCarteira.setLayout(jpnCarteiraLayout);
        jpnCarteiraLayout.setHorizontalGroup(
            jpnCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jpnCarteiraLayout.setVerticalGroup(
            jpnCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCarteiraLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnCarteira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnCarteira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpnCarteira;
    private javax.swing.JTable tbCarteira01;
    private javax.swing.JTable tbCarteira02;
    private javax.swing.JTable tbCarteira03;
    // End of variables declaration//GEN-END:variables
}
