/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemBolsa;

/**
 *
 * @author derp_
 */
public class HomeBroker extends javax.swing.JInternalFrame {

    /**
     * Creates new form HomeBroker
     */
    public HomeBroker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnBroker = new javax.swing.JDesktopPane();
        menuBroker = new javax.swing.JMenuBar();
        menu3 = new javax.swing.JMenu();
        menuComprar = new javax.swing.JMenuItem();
        menuVender = new javax.swing.JMenu();
        menuVender02 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuBook = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Home Broker");

        javax.swing.GroupLayout jpnBrokerLayout = new javax.swing.GroupLayout(jpnBroker);
        jpnBroker.setLayout(jpnBrokerLayout);
        jpnBrokerLayout.setHorizontalGroup(
            jpnBrokerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        jpnBrokerLayout.setVerticalGroup(
            jpnBrokerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        menu3.setText("Comprar");

        menuComprar.setText("Comprar");
        menuComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuComprarActionPerformed(evt);
            }
        });
        menu3.add(menuComprar);

        menuBroker.add(menu3);

        menuVender.setText("Vender");

        menuVender02.setText("Vender");
        menuVender02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVender02ActionPerformed(evt);
            }
        });
        menuVender.add(menuVender02);

        menuBroker.add(menuVender);

        jMenu1.setText("Book de Ofertas");

        menuBook.setText("Book de Ofertas");
        menuBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBookActionPerformed(evt);
            }
        });
        jMenu1.add(menuBook);

        menuBroker.add(jMenu1);

        setJMenuBar(menuBroker);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnBroker, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnBroker, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuComprarActionPerformed
       Comprar ob = new Comprar();
        jpnBroker.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_menuComprarActionPerformed

    private void menuVender02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVender02ActionPerformed
       Vender ob = new Vender();
        jpnBroker.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_menuVender02ActionPerformed

    private void menuBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBookActionPerformed
        BookOfertas ob = new  BookOfertas();
        jpnBroker.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_menuBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JDesktopPane jpnBroker;
    private javax.swing.JMenu menu3;
    private javax.swing.JMenuItem menuBook;
    private javax.swing.JMenuBar menuBroker;
    private javax.swing.JMenuItem menuComprar;
    private javax.swing.JMenu menuVender;
    private javax.swing.JMenuItem menuVender02;
    // End of variables declaration//GEN-END:variables
}
