/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemBolsa;

import javax.swing.JOptionPane;

/**
 *
 * @author derp_
 */
public class LoginCorretor extends javax.swing.JFrame {

    /**
     * Creates new form LoginCorretor
     */
    public LoginCorretor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnLoginOperador = new javax.swing.JDesktopPane();
        txtLoginOperador = new javax.swing.JTextField();
        txtSenhaOperador = new javax.swing.JPasswordField();
        btnLoginOperador = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnTelaLoginAcionista = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        btnCadastroCorreto = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Corretor");
        setResizable(false);

        jpnLoginOperador.setBackground(new java.awt.Color(204, 0, 0));

        txtLoginOperador.setText("admin");

        txtSenhaOperador.setText("admin");

        btnLoginOperador.setText("Entrar");
        btnLoginOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginOperadorActionPerformed(evt);
            }
        });
        btnLoginOperador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginOperadorKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel18.setText("Senha: ");

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel19.setText("Usuário: ");

        btnTelaLoginAcionista.setText("Voltar");
        btnTelaLoginAcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaLoginAcionistaActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("É acionista? Click no botão ao lado ->>>>");

        btnCadastroCorreto.setText("Cadastrar");
        btnCadastroCorreto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroCorretoActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Não é cadastrado?->>>");

        jpnLoginOperador.setLayer(txtLoginOperador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnLoginOperador.setLayer(txtSenhaOperador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnLoginOperador.setLayer(btnLoginOperador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnLoginOperador.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnLoginOperador.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnLoginOperador.setLayer(btnTelaLoginAcionista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnLoginOperador.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnLoginOperador.setLayer(btnCadastroCorreto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnLoginOperador.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpnLoginOperadorLayout = new javax.swing.GroupLayout(jpnLoginOperador);
        jpnLoginOperador.setLayout(jpnLoginOperadorLayout);
        jpnLoginOperadorLayout.setHorizontalGroup(
            jpnLoginOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginOperadorLayout.createSequentialGroup()
                .addGroup(jpnLoginOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnLoginOperadorLayout.createSequentialGroup()
                        .addContainerGap(275, Short.MAX_VALUE)
                        .addGroup(jpnLoginOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jpnLoginOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLoginOperador)
                            .addComponent(txtSenhaOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnLoginOperadorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpnLoginOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLoginOperadorLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18))
                            .addGroup(jpnLoginOperadorLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)))
                        .addGroup(jpnLoginOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLoginOperador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTelaLoginAcionista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCadastroCorreto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jpnLoginOperadorLayout.setVerticalGroup(
            jpnLoginOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginOperadorLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jpnLoginOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtLoginOperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jpnLoginOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtSenhaOperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoginOperador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jpnLoginOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroCorreto)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnLoginOperadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(btnTelaLoginAcionista))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpnLoginOperador, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private boolean ChekLoginOperador(String loginOperador, String senhaOperador){
        return  loginOperador.equals("admin") && senhaOperador.equals("admin");
    }
    private void btnLoginOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginOperadorActionPerformed
        if( this.ChekLoginOperador(txtLoginOperador.getText(), new String(txtSenhaOperador.getPassword()).trim() )){
            JOptionPane.showMessageDialog(null, "Olá corretor, bem vindo ao SystemBolsa!!!");
            CadastroEmpresa tela = new  CadastroEmpresa();
            tela.setVisible(true);
            dispose();
        }else{ JOptionPane.showMessageDialog(null, "Os dados informados estão incorretos! =/");

        }
    }//GEN-LAST:event_btnLoginOperadorActionPerformed

    private void btnLoginOperadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginOperadorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginOperadorKeyPressed

    private void btnTelaLoginAcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaLoginAcionistaActionPerformed
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTelaLoginAcionistaActionPerformed

    private void btnCadastroCorretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroCorretoActionPerformed
        CadastroCorretor tela = new CadastroCorretor();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCadastroCorretoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginCorretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginCorretor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroCorreto;
    private javax.swing.JButton btnLoginOperador;
    private javax.swing.JButton btnTelaLoginAcionista;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JDesktopPane jpnLoginOperador;
    private javax.swing.JTextField txtLoginOperador;
    private javax.swing.JPasswordField txtSenhaOperador;
    // End of variables declaration//GEN-END:variables
}
