/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemBolsa;

/**
 *
 * @author derp_
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCarteira = new javax.swing.JMenu();
        menuHistorico = new javax.swing.JMenu();
        menuCotacao = new javax.swing.JMenu();
        menuBrooker = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpnPrincipalLayout = new javax.swing.GroupLayout(jpnPrincipal);
        jpnPrincipal.setLayout(jpnPrincipalLayout);
        jpnPrincipalLayout.setHorizontalGroup(
            jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jpnPrincipalLayout.setVerticalGroup(
            jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        getContentPane().add(jpnPrincipal, java.awt.BorderLayout.CENTER);

        menuCarteira.setText("Carteira");
        menuCarteira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCarteiraMouseClicked(evt);
            }
        });
        menuCarteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCarteiraActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuCarteira);

        menuHistorico.setText("Histórico");
        menuHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHistoricoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuHistorico);

        menuCotacao.setText("Cotações");
        menuCotacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCotacaoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCotacao);

        menuBrooker.setText("Home Brooker");
        menuBrooker.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
                menuBrookerMenuCanceled(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
            }
        });
        menuBrooker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBrookerMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuBrooker);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCarteiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCarteiraMouseClicked
        TelaCarteira ob = new TelaCarteira();
        jpnPrincipal.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_menuCarteiraMouseClicked

    private void menuCarteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCarteiraActionPerformed

    }//GEN-LAST:event_menuCarteiraActionPerformed

    private void menuHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHistoricoMouseClicked
        TelaHistorico ob = new TelaHistorico();
        jpnPrincipal.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_menuHistoricoMouseClicked

    private void menuCotacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCotacaoMouseClicked
        TelaCotacao ob = new TelaCotacao();
        jpnPrincipal.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_menuCotacaoMouseClicked

    private void menuBrookerMenuCanceled(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuBrookerMenuCanceled
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBrookerMenuCanceled

    private void menuBrookerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBrookerMouseClicked
        TelaHomeBroker ob = new TelaHomeBroker();
        jpnPrincipal.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_menuBrookerMouseClicked

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
       System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jpnPrincipal;
    private javax.swing.JMenu menuBrooker;
    private javax.swing.JMenu menuCarteira;
    private javax.swing.JMenu menuCotacao;
    private javax.swing.JMenu menuHistorico;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
