/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemBolsa;

/**
 *
 * @author derp_
 */
public class TelaCotacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCotacao
     */
    public TelaCotacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnCotacao = new javax.swing.JDesktopPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbCotacao = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cotações");
        setToolTipText("Cotações");

        jpnCotacao.setBackground(new java.awt.Color(255, 51, 0));

        tbCotacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Papel", "Nome", "Maxima", "Minima", "Atual", "Oscila", "Negocios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCotacao.setGridColor(new java.awt.Color(255, 255, 255));
        tbCotacao.setSelectionBackground(new java.awt.Color(0, 0, 204));
        tbCotacao.setSelectionForeground(new java.awt.Color(0, 0, 255));
        tbCotacao.setShowHorizontalLines(false);
        tbCotacao.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tbCotacao);

        jLabel27.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 0, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Cotações");

        jpnCotacao.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCotacao.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpnCotacaoLayout = new javax.swing.GroupLayout(jpnCotacao);
        jpnCotacao.setLayout(jpnCotacaoLayout);
        jpnCotacaoLayout.setHorizontalGroup(
            jpnCotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCotacaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(451, 451, 451))
        );
        jpnCotacaoLayout.setVerticalGroup(
            jpnCotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCotacaoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel27)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpnCotacao, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel27;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JDesktopPane jpnCotacao;
    private javax.swing.JTable tbCotacao;
    // End of variables declaration//GEN-END:variables
}
