/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemBolsa;

/**
 *
 * @author derp_
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCarteira = new javax.swing.JMenu();
        MenuCarteira2 = new javax.swing.JMenuItem();
        menuHistorico = new javax.swing.JMenu();
        menuHistorico2 = new javax.swing.JMenuItem();
        menuCotacao = new javax.swing.JMenu();
        menuEmpresa2 = new javax.swing.JMenuItem();
        menuHomeBroker = new javax.swing.JMenu();
        menuHomeBroker2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SystemBolsa");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        javax.swing.GroupLayout jpnPrincipalLayout = new javax.swing.GroupLayout(jpnPrincipal);
        jpnPrincipal.setLayout(jpnPrincipalLayout);
        jpnPrincipalLayout.setHorizontalGroup(
            jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1209, Short.MAX_VALUE)
        );
        jpnPrincipalLayout.setVerticalGroup(
            jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        getContentPane().add(jpnPrincipal, java.awt.BorderLayout.CENTER);

        menuCarteira.setText("Carteira");
        menuCarteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCarteiraActionPerformed(evt);
            }
        });

        MenuCarteira2.setText("Carteira");
        MenuCarteira2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCarteira2ActionPerformed(evt);
            }
        });
        menuCarteira.add(MenuCarteira2);

        jMenuBar1.add(menuCarteira);

        menuHistorico.setText("Histórico");

        menuHistorico2.setText("Histórico");
        menuHistorico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHistorico2ActionPerformed(evt);
            }
        });
        menuHistorico.add(menuHistorico2);

        jMenuBar1.add(menuHistorico);

        menuCotacao.setText("Cotações");

        menuEmpresa2.setText("Cotações");
        menuEmpresa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpresa2ActionPerformed(evt);
            }
        });
        menuCotacao.add(menuEmpresa2);

        jMenuBar1.add(menuCotacao);

        menuHomeBroker.setText("Home Broker");

        menuHomeBroker2.setText("Home Broker");
        menuHomeBroker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHomeBroker2ActionPerformed(evt);
            }
        });
        menuHomeBroker.add(menuHomeBroker2);

        jMenuBar1.add(menuHomeBroker);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCarteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCarteiraActionPerformed
       
    }//GEN-LAST:event_menuCarteiraActionPerformed

    private void MenuCarteira2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCarteira2ActionPerformed
        Carteira ob = new Carteira();
        jpnPrincipal.add(ob);
        ob.setVisible(true);    }//GEN-LAST:event_MenuCarteira2ActionPerformed

    private void menuHistorico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHistorico2ActionPerformed
        Historico ob = new Historico();
        jpnPrincipal.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_menuHistorico2ActionPerformed

    private void menuEmpresa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpresa2ActionPerformed
       Cotacao ob = new Cotacao();
        jpnPrincipal.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_menuEmpresa2ActionPerformed

    private void menuHomeBroker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHomeBroker2ActionPerformed
        HomeBroker ob = new HomeBroker();
        jpnPrincipal.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_menuHomeBroker2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCarteira2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jpnPrincipal;
    private javax.swing.JMenu menuCarteira;
    private javax.swing.JMenu menuCotacao;
    private javax.swing.JMenuItem menuEmpresa2;
    private javax.swing.JMenu menuHistorico;
    private javax.swing.JMenuItem menuHistorico2;
    private javax.swing.JMenu menuHomeBroker;
    private javax.swing.JMenuItem menuHomeBroker2;
    // End of variables declaration//GEN-END:variables
}
