/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemBolsa;

import java.awt.CardLayout;

/**
 *
 * @author derp_
 */
public class TelaPrincipal2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaPrincipal2
     */
    public TelaPrincipal2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnPrincipal = new javax.swing.JDesktopPane();
        jpnCard = new javax.swing.JDesktopPane();
        jpnCarteira = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCarteira01 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCarteira02 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbCarteira03 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jpnHistorico = new javax.swing.JDesktopPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbHistorico = new javax.swing.JTable();
        jpnCotacao = new javax.swing.JDesktopPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbCotacao = new javax.swing.JTable();
        jpnCompra = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPrecoAtualCompra = new javax.swing.JLabel();
        lblOscilaCompra = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblNegocioCompra = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblFatorCotCompra = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblLoteMinCompra = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblValorLotCompra = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        btnAcaoCompra = new javax.swing.JButton();
        txtAcaoCompra = new javax.swing.JFormattedTextField();
        txtPrecoCompra = new javax.swing.JFormattedTextField();
        txtQuantCompra = new javax.swing.JFormattedTextField();
        txtOrdemCompra = new javax.swing.JFormattedTextField();
        jpnBook = new javax.swing.JDesktopPane();
        btnPesquisaBook = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbBook = new javax.swing.JTable();
        txtPesquisaBook = new javax.swing.JFormattedTextField();
        jpnVenda = new javax.swing.JDesktopPane();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblNegocioVenda = new javax.swing.JLabel();
        lblPrecoAtualVenda = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblLucro = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblFatorCotVenda = new javax.swing.JLabel();
        lblValorLoteVenda = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ldlLoteMinVenda = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblCarteira = new javax.swing.JLabel();
        lblPrecoCompra = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnVenda = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAcaoVenda = new javax.swing.JButton();
        txtAcaoVenda = new javax.swing.JFormattedTextField();
        txtPrecoVenda = new javax.swing.JFormattedTextField();
        txtQuantAcaoVenda = new javax.swing.JFormattedTextField();
        txtOrdemVenda = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCarteira = new javax.swing.JMenu();
        menuHistorico = new javax.swing.JMenu();
        menuCotacao = new javax.swing.JMenu();
        menuHomeBroker = new javax.swing.JMenu();
        menuVender02 = new javax.swing.JMenuItem();
        menuBook = new javax.swing.JMenuItem();
        menuComprar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jpnPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jpnPrincipal.setLayout(new java.awt.CardLayout());

        jpnCard.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jpnCardLayout = new javax.swing.GroupLayout(jpnCard);
        jpnCard.setLayout(jpnCardLayout);
        jpnCardLayout.setHorizontalGroup(
            jpnCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1209, Short.MAX_VALUE)
        );
        jpnCardLayout.setVerticalGroup(
            jpnCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        jpnPrincipal.add(jpnCard, "jpnCard");

        jpnCarteira.setBackground(new java.awt.Color(0, 102, 102));

        tbCarteira01.setForeground(new java.awt.Color(255, 255, 255));
        tbCarteira01.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ativo", "Quantidade", "Valor compra", "Valor atual", "Total Compra", "Total Atual", "Lucro/Prejuizo", "%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCarteira01.setGridColor(new java.awt.Color(255, 255, 255));
        tbCarteira01.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbCarteira01);
        if (tbCarteira01.getColumnModel().getColumnCount() > 0) {
            tbCarteira01.getColumnModel().getColumn(0).setResizable(false);
            tbCarteira01.getColumnModel().getColumn(1).setResizable(false);
            tbCarteira01.getColumnModel().getColumn(2).setResizable(false);
            tbCarteira01.getColumnModel().getColumn(3).setResizable(false);
            tbCarteira01.getColumnModel().getColumn(4).setResizable(false);
            tbCarteira01.getColumnModel().getColumn(5).setResizable(false);
            tbCarteira01.getColumnModel().getColumn(6).setResizable(false);
            tbCarteira01.getColumnModel().getColumn(7).setResizable(false);
        }

        tbCarteira02.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "", "Total Compra", "Total Atual", "Lucro/Prejuizo", "%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCarteira02.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbCarteira02);
        if (tbCarteira02.getColumnModel().getColumnCount() > 0) {
            tbCarteira02.getColumnModel().getColumn(0).setResizable(false);
            tbCarteira02.getColumnModel().getColumn(1).setResizable(false);
            tbCarteira02.getColumnModel().getColumn(2).setResizable(false);
            tbCarteira02.getColumnModel().getColumn(3).setResizable(false);
            tbCarteira02.getColumnModel().getColumn(4).setResizable(false);
        }

        tbCarteira03.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"CONTA CORRENTE", null, null, null, null, null}
            },
            new String [] {
                "", "", "Disponível", "Em carteira", "Saldo", "%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCarteira03.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbCarteira03);
        if (tbCarteira03.getColumnModel().getColumnCount() > 0) {
            tbCarteira03.getColumnModel().getColumn(0).setResizable(false);
            tbCarteira03.getColumnModel().getColumn(1).setResizable(false);
            tbCarteira03.getColumnModel().getColumn(2).setResizable(false);
            tbCarteira03.getColumnModel().getColumn(3).setResizable(false);
            tbCarteira03.getColumnModel().getColumn(4).setResizable(false);
            tbCarteira03.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel26.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 0, 0));
        jLabel26.setText("Carteira de ações");

        jpnCarteira.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCarteira.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCarteira.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCarteira.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpnCarteiraLayout = new javax.swing.GroupLayout(jpnCarteira);
        jpnCarteira.setLayout(jpnCarteiraLayout);
        jpnCarteiraLayout.setHorizontalGroup(
            jpnCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane3)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1209, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCarteiraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(472, 472, 472))
        );
        jpnCarteiraLayout.setVerticalGroup(
            jpnCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCarteiraLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );

        jpnPrincipal.add(jpnCarteira, "jpnCarteira");

        jpnHistorico.setBackground(new java.awt.Color(102, 255, 102));

        tbHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Hora", "Descrição", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHistorico.setGridColor(new java.awt.Color(255, 255, 255));
        tbHistorico.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tbHistorico);
        if (tbHistorico.getColumnModel().getColumnCount() > 0) {
            tbHistorico.getColumnModel().getColumn(0).setResizable(false);
            tbHistorico.getColumnModel().getColumn(1).setResizable(false);
            tbHistorico.getColumnModel().getColumn(2).setResizable(false);
            tbHistorico.getColumnModel().getColumn(3).setResizable(false);
        }

        jpnHistorico.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpnHistoricoLayout = new javax.swing.GroupLayout(jpnHistorico);
        jpnHistorico.setLayout(jpnHistoricoLayout);
        jpnHistoricoLayout.setHorizontalGroup(
            jpnHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1209, Short.MAX_VALUE)
        );
        jpnHistoricoLayout.setVerticalGroup(
            jpnHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHistoricoLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jpnPrincipal.add(jpnHistorico, "jpnHistorico");

        jpnCotacao.setBackground(new java.awt.Color(255, 51, 0));

        tbCotacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Papel", "Nome", "Maxima", "Minima", "Atual", "Oscila", "Negocios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCotacao.setGridColor(new java.awt.Color(255, 255, 255));
        tbCotacao.setSelectionBackground(new java.awt.Color(0, 0, 204));
        tbCotacao.setSelectionForeground(new java.awt.Color(0, 0, 255));
        tbCotacao.setShowHorizontalLines(false);
        tbCotacao.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tbCotacao);
        if (tbCotacao.getColumnModel().getColumnCount() > 0) {
            tbCotacao.getColumnModel().getColumn(0).setResizable(false);
            tbCotacao.getColumnModel().getColumn(1).setResizable(false);
            tbCotacao.getColumnModel().getColumn(2).setResizable(false);
            tbCotacao.getColumnModel().getColumn(3).setResizable(false);
            tbCotacao.getColumnModel().getColumn(4).setResizable(false);
            tbCotacao.getColumnModel().getColumn(5).setResizable(false);
            tbCotacao.getColumnModel().getColumn(6).setResizable(false);
        }

        jpnCotacao.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpnCotacaoLayout = new javax.swing.GroupLayout(jpnCotacao);
        jpnCotacao.setLayout(jpnCotacaoLayout);
        jpnCotacaoLayout.setHorizontalGroup(
            jpnCotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1209, Short.MAX_VALUE)
        );
        jpnCotacaoLayout.setVerticalGroup(
            jpnCotacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCotacaoLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jpnPrincipal.add(jpnCotacao, "jpnCotacao");

        jpnCompra.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("Ações");

        jLabel2.setText("Preço R$");

        jLabel3.setText("Quantidade");

        jLabel4.setText("Ordem R$");

        jLabel6.setText("Preço atual: ");

        lblPrecoAtualCompra.setText("0,00");

        lblOscilaCompra.setText("0.00");

        jLabel5.setText("Oscilação: ");

        jLabel7.setText("Negocios: ");

        lblNegocioCompra.setText("0");

        jLabel8.setText("Fator de cotação: ");

        lblFatorCotCompra.setText("0");

        jLabel9.setText("Lote minímo: ");

        lblLoteMinCompra.setText("0");

        jLabel21.setText("(");

        lblValorLotCompra.setText("0,00");

        jLabel19.setText(")");

        btnComprar.setText("Prosseguir");

        btnAcaoCompra.setText("ox");

        jpnCompra.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(lblPrecoAtualCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(lblOscilaCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(lblNegocioCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(lblFatorCotCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(lblLoteMinCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(lblValorLotCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(btnComprar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(btnAcaoCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(txtAcaoCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(txtPrecoCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(txtQuantCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(txtOrdemCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpnCompraLayout = new javax.swing.GroupLayout(jpnCompra);
        jpnCompra.setLayout(jpnCompraLayout);
        jpnCompraLayout.setHorizontalGroup(
            jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCompraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnComprar)
                    .addGroup(jpnCompraLayout.createSequentialGroup()
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(47, 47, 47))
                            .addGroup(jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(66, 66, 66)))
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAcaoCompra)
                            .addComponent(txtPrecoCompra)
                            .addComponent(txtQuantCompra)
                            .addComponent(txtOrdemCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))))
                .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnCompraLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLoteMinCompra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorLotCompra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lblNegocioCompra))
                            .addGroup(jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(lblOscilaCompra))
                            .addGroup(jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPrecoAtualCompra))
                            .addGroup(jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFatorCotCompra))))
                    .addGroup(jpnCompraLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAcaoCompra)))
                .addContainerGap(669, Short.MAX_VALUE))
        );
        jpnCompraLayout.setVerticalGroup(
            jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCompraLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnCompraLayout.createSequentialGroup()
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblPrecoAtualCompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblOscilaCompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblNegocioCompra))
                        .addGap(5, 5, 5)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblFatorCotCompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblLoteMinCompra)
                            .addComponent(jLabel21)
                            .addComponent(lblValorLotCompra)
                            .addComponent(jLabel19)))
                    .addGroup(jpnCompraLayout.createSequentialGroup()
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnAcaoCompra)
                            .addComponent(txtAcaoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtQuantCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtOrdemCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addComponent(btnComprar)))
                .addContainerGap(351, Short.MAX_VALUE))
        );

        jpnPrincipal.add(jpnCompra, "jpnCompra");

        jpnBook.setBackground(new java.awt.Color(255, 255, 153));

        btnPesquisaBook.setText("Pesquisar");

        tbBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compras", "Vendas"
            }
        ));
        jScrollPane6.setViewportView(tbBook);

        jpnBook.setLayer(btnPesquisaBook, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnBook.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnBook.setLayer(txtPesquisaBook, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpnBookLayout = new javax.swing.GroupLayout(jpnBook);
        jpnBook.setLayout(jpnBookLayout);
        jpnBookLayout.setHorizontalGroup(
            jpnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPesquisaBook)
                .addGap(18, 18, 18)
                .addGroup(jpnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(txtPesquisaBook))
                .addContainerGap(863, Short.MAX_VALUE))
        );
        jpnBookLayout.setVerticalGroup(
            jpnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisaBook)
                    .addComponent(txtPesquisaBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        jpnPrincipal.add(jpnBook, "jpnBook");

        jpnVenda.setBackground(new java.awt.Color(153, 0, 153));
        jpnVenda.setToolTipText("");

        jLabel17.setText("Fator de cotação: ");

        jLabel15.setText("Negocios: ");

        lblNegocioVenda.setText("0");

        lblPrecoAtualVenda.setText("0,00");

        jLabel16.setText("(");

        lblLucro.setText("0.00");

        jLabel18.setText("%)");

        jLabel14.setText("Preço atual: ");

        lblFatorCotVenda.setText("0");

        lblValorLoteVenda.setText("0,00");

        jLabel20.setText(")");

        jLabel22.setText("(");

        jLabel23.setText("Lote minímo: ");

        ldlLoteMinVenda.setText("0");

        jLabel24.setText("Em sua carteira: ");

        lblCarteira.setText("0");

        lblPrecoCompra.setText("0,00");

        jLabel25.setText("Preço de compra: ");

        btnVenda.setText("Prosseguir");

        jLabel13.setText("Ordem R$");

        jLabel12.setText("Quantidade");

        jLabel11.setText("Preço R$");

        jLabel10.setText("Ações");

        btnAcaoVenda.setText("ok");

        jpnVenda.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(lblNegocioVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(lblPrecoAtualVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(lblLucro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(lblFatorCotVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(lblValorLoteVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(ldlLoteMinVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(lblCarteira, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(lblPrecoCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(btnVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(btnAcaoVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(txtAcaoVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(txtPrecoVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(txtQuantAcaoVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(txtOrdemVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpnVendaLayout = new javax.swing.GroupLayout(jpnVenda);
        jpnVenda.setLayout(jpnVendaLayout);
        jpnVendaLayout.setHorizontalGroup(
            jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnVendaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnVendaLayout.createSequentialGroup()
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnVendaLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(52, 52, 52))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnVendaLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(39, 39, 39))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnVendaLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(47, 47, 47)))
                            .addGroup(jpnVendaLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(66, 66, 66)))
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAcaoVenda)
                            .addComponent(txtPrecoVenda)
                            .addComponent(txtQuantAcaoVenda)
                            .addComponent(txtOrdemVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                    .addComponent(btnVenda))
                .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnVendaLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnVendaLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPrecoCompra))
                            .addGroup(jpnVendaLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCarteira))
                            .addGroup(jpnVendaLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(lblNegocioVenda))
                            .addGroup(jpnVendaLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPrecoAtualVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLucro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addGroup(jpnVendaLayout.createSequentialGroup()
                                .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jpnVendaLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ldlLoteMinVenda)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22))
                                    .addComponent(jLabel17))
                                .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpnVendaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFatorCotVenda))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnVendaLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(lblValorLoteVenda)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20))))))
                    .addGroup(jpnVendaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAcaoVenda)))
                .addGap(656, 656, 656))
        );
        jpnVendaLayout.setVerticalGroup(
            jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnVendaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnVendaLayout.createSequentialGroup()
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblPrecoAtualVenda)
                            .addComponent(jLabel16)
                            .addComponent(lblLucro)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lblNegocioVenda))
                        .addGap(5, 5, 5)
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(lblFatorCotVenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(lblValorLoteVenda)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(ldlLoteMinVenda)))
                    .addGroup(jpnVendaLayout.createSequentialGroup()
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(btnAcaoVenda)
                            .addComponent(txtAcaoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtQuantAcaoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtOrdemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(btnVenda)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblCarteira))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lblPrecoCompra))
                .addContainerGap(349, Short.MAX_VALUE))
        );

        jpnPrincipal.add(jpnVenda, "jpnVenda");

        menuCarteira.setText("Carteira");
        menuCarteira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCarteiraMouseClicked(evt);
            }
        });
        menuCarteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCarteiraActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuCarteira);

        menuHistorico.setText("Histórico");
        menuHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHistoricoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuHistorico);

        menuCotacao.setText("Cotações");
        menuCotacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCotacaoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCotacao);

        menuHomeBroker.setText("Home Broker");

        menuVender02.setText("Vender");
        menuVender02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVender02ActionPerformed(evt);
            }
        });
        menuHomeBroker.add(menuVender02);

        menuBook.setText("Book de Ofertas");
        menuBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBookActionPerformed(evt);
            }
        });
        menuHomeBroker.add(menuBook);

        menuComprar.setText("Comprar");
        menuComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuComprarActionPerformed(evt);
            }
        });
        menuHomeBroker.add(menuComprar);

        jMenuBar1.add(menuHomeBroker);

        jMenu1.setText("Sair");

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jpnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(jpnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCarteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCarteiraActionPerformed

    }//GEN-LAST:event_menuCarteiraActionPerformed

    private void menuComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuComprarActionPerformed
        CardLayout cl = (CardLayout) jpnPrincipal.getLayout();
        cl.show(jpnPrincipal, "jpnCompra");
    }//GEN-LAST:event_menuComprarActionPerformed

    private void menuVender02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVender02ActionPerformed
        CardLayout cl = (CardLayout) jpnPrincipal.getLayout();
        cl.show(jpnPrincipal, "jpnVenda");
    }//GEN-LAST:event_menuVender02ActionPerformed

    private void menuBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBookActionPerformed
        CardLayout cl = (CardLayout) jpnPrincipal.getLayout();
        cl.show(jpnPrincipal, "jpnBook");
    }//GEN-LAST:event_menuBookActionPerformed

    private void menuCarteiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCarteiraMouseClicked
        CardLayout cl = (CardLayout) jpnPrincipal.getLayout();
        cl.show(jpnPrincipal, "jpnCarteira");
    }//GEN-LAST:event_menuCarteiraMouseClicked

    private void menuHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHistoricoMouseClicked
         CardLayout cl = (CardLayout) jpnPrincipal.getLayout();
        cl.show(jpnPrincipal, "jpnHistorico");
    }//GEN-LAST:event_menuHistoricoMouseClicked

    private void menuCotacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCotacaoMouseClicked
       CardLayout cl = (CardLayout) jpnPrincipal.getLayout();
        cl.show(jpnPrincipal, "jpnCotacao");
    }//GEN-LAST:event_menuCotacaoMouseClicked

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed

    }//GEN-LAST:event_menuSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcaoCompra;
    private javax.swing.JButton btnAcaoVenda;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnPesquisaBook;
    private javax.swing.JButton btnVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JDesktopPane jpnBook;
    private javax.swing.JDesktopPane jpnCard;
    private javax.swing.JDesktopPane jpnCarteira;
    private javax.swing.JDesktopPane jpnCompra;
    private javax.swing.JDesktopPane jpnCotacao;
    private javax.swing.JDesktopPane jpnHistorico;
    private javax.swing.JDesktopPane jpnPrincipal;
    private javax.swing.JDesktopPane jpnVenda;
    private javax.swing.JLabel lblCarteira;
    private javax.swing.JLabel lblFatorCotCompra;
    private javax.swing.JLabel lblFatorCotVenda;
    private javax.swing.JLabel lblLoteMinCompra;
    private javax.swing.JLabel lblLucro;
    private javax.swing.JLabel lblNegocioCompra;
    private javax.swing.JLabel lblNegocioVenda;
    private javax.swing.JLabel lblOscilaCompra;
    private javax.swing.JLabel lblPrecoAtualCompra;
    private javax.swing.JLabel lblPrecoAtualVenda;
    private javax.swing.JLabel lblPrecoCompra;
    private javax.swing.JLabel lblValorLotCompra;
    private javax.swing.JLabel lblValorLoteVenda;
    private javax.swing.JLabel ldlLoteMinVenda;
    private javax.swing.JMenuItem menuBook;
    private javax.swing.JMenu menuCarteira;
    private javax.swing.JMenuItem menuComprar;
    private javax.swing.JMenu menuCotacao;
    private javax.swing.JMenu menuHistorico;
    private javax.swing.JMenu menuHomeBroker;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuVender02;
    private javax.swing.JTable tbBook;
    private javax.swing.JTable tbCarteira01;
    private javax.swing.JTable tbCarteira02;
    private javax.swing.JTable tbCarteira03;
    private javax.swing.JTable tbCotacao;
    private javax.swing.JTable tbHistorico;
    private javax.swing.JFormattedTextField txtAcaoCompra;
    private javax.swing.JFormattedTextField txtAcaoVenda;
    private javax.swing.JFormattedTextField txtOrdemCompra;
    private javax.swing.JFormattedTextField txtOrdemVenda;
    private javax.swing.JFormattedTextField txtPesquisaBook;
    private javax.swing.JFormattedTextField txtPrecoCompra;
    private javax.swing.JFormattedTextField txtPrecoVenda;
    private javax.swing.JFormattedTextField txtQuantAcaoVenda;
    private javax.swing.JFormattedTextField txtQuantCompra;
    // End of variables declaration//GEN-END:variables
}
