/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemBolsa;

/**
 *
 * @author derp_
 */
public class TelaCarteira extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCarteira
     */
    public TelaCarteira() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnCarteira = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCarteira01 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCarteira02 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbCarteira03 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Carteira de Ações");
        setToolTipText("Carteira de Ações");

        jpnCarteira.setBackground(new java.awt.Color(0, 102, 102));

        tbCarteira01.setForeground(new java.awt.Color(255, 255, 255));
        tbCarteira01.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ativo", "Quantidade", "Valor compra", "Valor atual", "Total Compra", "Total Atual", "Lucro/Prejuizo", "%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCarteira01.setGridColor(new java.awt.Color(255, 255, 255));
        tbCarteira01.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbCarteira01);

        tbCarteira02.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "", "Total Compra", "Total Atual", "Lucro/Prejuizo", "%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCarteira02.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbCarteira02);

        tbCarteira03.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"CONTA CORRENTE", null, null, null, null, null}
            },
            new String [] {
                "", "", "Disponível", "Em carteira", "Saldo", "%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCarteira03.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbCarteira03);

        jLabel26.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 0, 0));
        jLabel26.setText("Carteira de ações");

        jpnCarteira.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCarteira.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCarteira.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCarteira.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpnCarteiraLayout = new javax.swing.GroupLayout(jpnCarteira);
        jpnCarteira.setLayout(jpnCarteiraLayout);
        jpnCarteiraLayout.setHorizontalGroup(
            jpnCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane3)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCarteiraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(472, 472, 472))
        );
        jpnCarteiraLayout.setVerticalGroup(
            jpnCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCarteiraLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );

        getContentPane().add(jpnCarteira, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel26;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDesktopPane jpnCarteira;
    private javax.swing.JTable tbCarteira01;
    private javax.swing.JTable tbCarteira02;
    private javax.swing.JTable tbCarteira03;
    // End of variables declaration//GEN-END:variables
}
