/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemBolsa;

import java.awt.CardLayout;

/**
 *
 * @author derp_
 */
public class TelaHomeBroker extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaHomeBroker
     */
    public TelaHomeBroker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnBrooker = new javax.swing.JDesktopPane();
        jpnMenuBrooker = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jpnCompra = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblPrecoAtualCompra = new javax.swing.JLabel();
        lblOscilaCompra = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblNegocioCompra = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblFatorCotCompra = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblLoteMinCompra = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblValorLotCompra = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        btnAcaoCompra = new javax.swing.JButton();
        txtAcaoCompra = new javax.swing.JFormattedTextField();
        txtPrecoCompra = new javax.swing.JFormattedTextField();
        txtQuantCompra = new javax.swing.JFormattedTextField();
        txtOrdemCompra = new javax.swing.JFormattedTextField();
        jpnBook = new javax.swing.JDesktopPane();
        btnPesquisaBook = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbBook = new javax.swing.JTable();
        txtPesquisaBook = new javax.swing.JFormattedTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbBook1 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbBook2 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        tbBook3 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        tbBook4 = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        tbBook5 = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        tbBook6 = new javax.swing.JTable();
        jScrollPane13 = new javax.swing.JScrollPane();
        tbBook7 = new javax.swing.JTable();
        jpnVenda = new javax.swing.JDesktopPane();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblNegocioVenda = new javax.swing.JLabel();
        lblPrecoAtualVenda = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblLucro = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblFatorCotVenda = new javax.swing.JLabel();
        lblValorLoteVenda = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ldlLoteMinVenda = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblCarteira = new javax.swing.JLabel();
        lblPrecoCompra = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnVenda = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAcaoVenda = new javax.swing.JButton();
        txtAcaoVenda = new javax.swing.JFormattedTextField();
        txtPrecoVenda = new javax.swing.JFormattedTextField();
        txtQuantAcaoVenda = new javax.swing.JFormattedTextField();
        txtOrdemVenda = new javax.swing.JFormattedTextField();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Home Broker");
        setToolTipText("Home Broker");

        jpnBrooker.setBackground(new java.awt.Color(255, 255, 153));
        jpnBrooker.setPreferredSize(new java.awt.Dimension(1000, 400));
        jpnBrooker.setLayout(new java.awt.CardLayout());

        jpnMenuBrooker.setBackground(new java.awt.Color(204, 204, 204));
        jpnMenuBrooker.setPreferredSize(new java.awt.Dimension(1000, 400));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton1.setText("Comprar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton2.setText("Vender");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton3.setText("Book de ofertas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jpnMenuBrooker.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnMenuBrooker.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnMenuBrooker.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpnMenuBrookerLayout = new javax.swing.GroupLayout(jpnMenuBrooker);
        jpnMenuBrooker.setLayout(jpnMenuBrookerLayout);
        jpnMenuBrookerLayout.setHorizontalGroup(
            jpnMenuBrookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMenuBrookerLayout.createSequentialGroup()
                .addContainerGap(473, Short.MAX_VALUE)
                .addGroup(jpnMenuBrookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        jpnMenuBrookerLayout.setVerticalGroup(
            jpnMenuBrookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuBrookerLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jpnBrooker.add(jpnMenuBrooker, "jpnMenuBrooker");

        jpnCompra.setBackground(new java.awt.Color(255, 204, 204));
        jpnCompra.setPreferredSize(new java.awt.Dimension(1000, 400));

        jLabel1.setText("Ações");

        jLabel2.setText("Preço R$");

        jLabel3.setText("Quantidade");

        jLabel4.setText("Ordem R$");

        jLabel6.setText("Preço atual: ");

        lblPrecoAtualCompra.setText("0,00");

        lblOscilaCompra.setText("0.00");

        jLabel5.setText("Oscilação: ");

        jLabel7.setText("Negocios: ");

        lblNegocioCompra.setText("0");

        jLabel8.setText("Fator de cotação: ");

        lblFatorCotCompra.setText("0");

        jLabel9.setText("Lote minímo: ");

        lblLoteMinCompra.setText("0");

        jLabel21.setText("(");

        lblValorLotCompra.setText("0,00");

        jLabel19.setText(")");

        btnComprar.setText("Prosseguir");

        btnAcaoCompra.setText("ok");

        jpnCompra.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(lblPrecoAtualCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(lblOscilaCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(lblNegocioCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(lblFatorCotCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(lblLoteMinCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(lblValorLotCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(btnComprar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(btnAcaoCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(txtAcaoCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(txtPrecoCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(txtQuantCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnCompra.setLayer(txtOrdemCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpnCompraLayout = new javax.swing.GroupLayout(jpnCompra);
        jpnCompra.setLayout(jpnCompraLayout);
        jpnCompraLayout.setHorizontalGroup(
            jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCompraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnComprar)
                    .addGroup(jpnCompraLayout.createSequentialGroup()
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(47, 47, 47))
                            .addGroup(jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(66, 66, 66)))
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAcaoCompra)
                            .addComponent(txtPrecoCompra)
                            .addComponent(txtQuantCompra)
                            .addComponent(txtOrdemCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))))
                .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnCompraLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLoteMinCompra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValorLotCompra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(lblNegocioCompra))
                            .addGroup(jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(lblOscilaCompra))
                            .addGroup(jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPrecoAtualCompra))
                            .addGroup(jpnCompraLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFatorCotCompra))))
                    .addGroup(jpnCompraLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAcaoCompra)))
                .addContainerGap(460, Short.MAX_VALUE))
        );
        jpnCompraLayout.setVerticalGroup(
            jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCompraLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnCompraLayout.createSequentialGroup()
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblPrecoAtualCompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblOscilaCompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblNegocioCompra))
                        .addGap(5, 5, 5)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblFatorCotCompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblLoteMinCompra)
                            .addComponent(jLabel21)
                            .addComponent(lblValorLotCompra)
                            .addComponent(jLabel19)))
                    .addGroup(jpnCompraLayout.createSequentialGroup()
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnAcaoCompra)
                            .addComponent(txtAcaoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtQuantCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jpnCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtOrdemCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addComponent(btnComprar)))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jpnBrooker.add(jpnCompra, "jpnCompra");

        jpnBook.setBackground(new java.awt.Color(255, 255, 153));
        jpnBook.setPreferredSize(new java.awt.Dimension(1000, 400));

        btnPesquisaBook.setText("Pesquisar");

        tbBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compras", "Vendas"
            }
        ));
        jScrollPane6.setViewportView(tbBook);

        tbBook1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compras", "Vendas"
            }
        ));
        jScrollPane7.setViewportView(tbBook1);

        tbBook2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compras", "Vendas"
            }
        ));
        jScrollPane8.setViewportView(tbBook2);

        tbBook3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compras", "Vendas"
            }
        ));
        jScrollPane9.setViewportView(tbBook3);

        tbBook4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compras", "Vendas"
            }
        ));
        jScrollPane10.setViewportView(tbBook4);

        tbBook5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compras", "Vendas"
            }
        ));
        jScrollPane11.setViewportView(tbBook5);

        tbBook6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compras", "Vendas"
            }
        ));
        jScrollPane12.setViewportView(tbBook6);

        tbBook7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compras", "Vendas"
            }
        ));
        jScrollPane13.setViewportView(tbBook7);

        jpnBook.setLayer(btnPesquisaBook, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnBook.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnBook.setLayer(txtPesquisaBook, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnBook.setLayer(jScrollPane7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnBook.setLayer(jScrollPane8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnBook.setLayer(jScrollPane9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnBook.setLayer(jScrollPane10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnBook.setLayer(jScrollPane11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnBook.setLayer(jScrollPane12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnBook.setLayer(jScrollPane13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpnBookLayout = new javax.swing.GroupLayout(jpnBook);
        jpnBook.setLayout(jpnBookLayout);
        jpnBookLayout.setHorizontalGroup(
            jpnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBookLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btnPesquisaBook)
                .addGap(6, 6, 6)
                .addGroup(jpnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnBookLayout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(jpnBookLayout.createSequentialGroup()
                        .addGroup(jpnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPesquisaBook, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jpnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jpnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jpnBookLayout.setVerticalGroup(
            jpnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBookLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jpnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisaBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaBook))
                .addGap(29, 29, 29)
                .addGroup(jpnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnBookLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnBookLayout.createSequentialGroup()
                        .addGroup(jpnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpnBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jpnBrooker.add(jpnBook, "jpnBook");

        jpnVenda.setBackground(new java.awt.Color(153, 0, 153));
        jpnVenda.setToolTipText("");
        jpnVenda.setPreferredSize(new java.awt.Dimension(1000, 400));

        jLabel17.setText("Fator de cotação: ");

        jLabel15.setText("Negocios: ");

        lblNegocioVenda.setText("0");

        lblPrecoAtualVenda.setText("0,00");

        jLabel16.setText("(");

        lblLucro.setText("0.00");

        jLabel18.setText("%)");

        jLabel14.setText("Preço atual: ");

        lblFatorCotVenda.setText("0");

        lblValorLoteVenda.setText("0,00");

        jLabel20.setText(")");

        jLabel22.setText("(");

        jLabel23.setText("Lote minímo: ");

        ldlLoteMinVenda.setText("0");

        jLabel24.setText("Em sua carteira: ");

        lblCarteira.setText("0");

        lblPrecoCompra.setText("0,00");

        jLabel25.setText("Preço de compra: ");

        btnVenda.setText("Prosseguir");

        jLabel13.setText("Ordem R$");

        jLabel12.setText("Quantidade");

        jLabel11.setText("Preço R$");

        jLabel10.setText("Ações");

        btnAcaoVenda.setText("ok");

        jpnVenda.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(lblNegocioVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(lblPrecoAtualVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(lblLucro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(lblFatorCotVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(lblValorLoteVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(ldlLoteMinVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(lblCarteira, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(lblPrecoCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(btnVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(btnAcaoVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(txtAcaoVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(txtPrecoVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(txtQuantAcaoVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnVenda.setLayer(txtOrdemVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpnVendaLayout = new javax.swing.GroupLayout(jpnVenda);
        jpnVenda.setLayout(jpnVendaLayout);
        jpnVendaLayout.setHorizontalGroup(
            jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnVendaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnVendaLayout.createSequentialGroup()
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnVendaLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(52, 52, 52))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnVendaLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(39, 39, 39))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnVendaLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(47, 47, 47)))
                            .addGroup(jpnVendaLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(66, 66, 66)))
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecoVenda)
                            .addComponent(txtQuantAcaoVenda)
                            .addComponent(txtOrdemVenda)
                            .addComponent(txtAcaoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnVenda))
                .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnVendaLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnVendaLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPrecoCompra))
                            .addGroup(jpnVendaLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCarteira))
                            .addGroup(jpnVendaLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(lblNegocioVenda))
                            .addGroup(jpnVendaLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPrecoAtualVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLucro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addGroup(jpnVendaLayout.createSequentialGroup()
                                .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jpnVendaLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ldlLoteMinVenda)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22))
                                    .addComponent(jLabel17))
                                .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpnVendaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFatorCotVenda))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnVendaLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(lblValorLoteVenda)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20))))))
                    .addGroup(jpnVendaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAcaoVenda)))
                .addGap(656, 656, 656))
        );
        jpnVendaLayout.setVerticalGroup(
            jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnVendaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnVendaLayout.createSequentialGroup()
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblPrecoAtualVenda)
                            .addComponent(jLabel16)
                            .addComponent(lblLucro)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lblNegocioVenda))
                        .addGap(5, 5, 5)
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(lblFatorCotVenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(lblValorLoteVenda)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(ldlLoteMinVenda)))
                    .addGroup(jpnVendaLayout.createSequentialGroup()
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(btnAcaoVenda)
                            .addComponent(txtAcaoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtQuantAcaoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtOrdemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(btnVenda)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblCarteira))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lblPrecoCompra))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jpnBrooker.add(jpnVenda, "jpnVenda");

        getContentPane().add(jpnBrooker, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     CardLayout cl = (CardLayout) jpnBrooker.getLayout();
     cl.show(jpnBrooker, "jpnCompra");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout cl = (CardLayout) jpnBrooker.getLayout();
        cl.show(jpnBrooker, "jpnVenda");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         CardLayout cl = (CardLayout) jpnBrooker.getLayout();
         cl.show(jpnBrooker, "jpnBook");
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcaoCompra;
    private javax.swing.JButton btnAcaoVenda;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnPesquisaBook;
    private javax.swing.JButton btnVenda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JDesktopPane jpnBook;
    private javax.swing.JDesktopPane jpnBrooker;
    private javax.swing.JDesktopPane jpnCompra;
    private javax.swing.JDesktopPane jpnMenuBrooker;
    private javax.swing.JDesktopPane jpnVenda;
    private javax.swing.JLabel lblCarteira;
    private javax.swing.JLabel lblFatorCotCompra;
    private javax.swing.JLabel lblFatorCotVenda;
    private javax.swing.JLabel lblLoteMinCompra;
    private javax.swing.JLabel lblLucro;
    private javax.swing.JLabel lblNegocioCompra;
    private javax.swing.JLabel lblNegocioVenda;
    private javax.swing.JLabel lblOscilaCompra;
    private javax.swing.JLabel lblPrecoAtualCompra;
    private javax.swing.JLabel lblPrecoAtualVenda;
    private javax.swing.JLabel lblPrecoCompra;
    private javax.swing.JLabel lblValorLotCompra;
    private javax.swing.JLabel lblValorLoteVenda;
    private javax.swing.JLabel ldlLoteMinVenda;
    private javax.swing.JTable tbBook;
    private javax.swing.JTable tbBook1;
    private javax.swing.JTable tbBook2;
    private javax.swing.JTable tbBook3;
    private javax.swing.JTable tbBook4;
    private javax.swing.JTable tbBook5;
    private javax.swing.JTable tbBook6;
    private javax.swing.JTable tbBook7;
    private javax.swing.JFormattedTextField txtAcaoCompra;
    private javax.swing.JFormattedTextField txtAcaoVenda;
    private javax.swing.JFormattedTextField txtOrdemCompra;
    private javax.swing.JFormattedTextField txtOrdemVenda;
    private javax.swing.JFormattedTextField txtPesquisaBook;
    private javax.swing.JFormattedTextField txtPrecoCompra;
    private javax.swing.JFormattedTextField txtPrecoVenda;
    private javax.swing.JFormattedTextField txtQuantAcaoVenda;
    private javax.swing.JFormattedTextField txtQuantCompra;
    // End of variables declaration//GEN-END:variables
}
