/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemBolsa;

/**
 *
 * @author derp_
 */
public class TelaHistorico extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaHistorico
     */
    public TelaHistorico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnHistorico = new javax.swing.JDesktopPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbHistorico = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();

        setClosable(true);
        setForeground(new java.awt.Color(0, 0, 153));
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Histórico");
        setToolTipText("Histórico");

        jpnHistorico.setBackground(new java.awt.Color(102, 255, 102));

        tbHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Hora", "Descrição", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHistorico.setGridColor(new java.awt.Color(255, 255, 255));
        tbHistorico.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tbHistorico);

        jLabel28.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 0, 0));
        jLabel28.setText("Histórico");

        jpnHistorico.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpnHistorico.setLayer(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpnHistoricoLayout = new javax.swing.GroupLayout(jpnHistorico);
        jpnHistorico.setLayout(jpnHistoricoLayout);
        jpnHistoricoLayout.setHorizontalGroup(
            jpnHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnHistoricoLayout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(544, 544, 544))
        );
        jpnHistoricoLayout.setVerticalGroup(
            jpnHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHistoricoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpnHistorico, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel28;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JDesktopPane jpnHistorico;
    private javax.swing.JTable tbHistorico;
    // End of variables declaration//GEN-END:variables
}
