/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SystemBolsa;

import java.awt.CardLayout;

/**
 *
 * @author derp_
 */
public class TelaMenuPrincipal extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaPrincipal2
     */
    public TelaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCarteira = new javax.swing.JMenu();
        menuHistorico = new javax.swing.JMenu();
        menuCotacao = new javax.swing.JMenu();
        menuBrooker = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jpnPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpnPrincipalLayout = new javax.swing.GroupLayout(jpnPrincipal);
        jpnPrincipal.setLayout(jpnPrincipalLayout);
        jpnPrincipalLayout.setHorizontalGroup(
            jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        jpnPrincipalLayout.setVerticalGroup(
            jpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        getContentPane().add(jpnPrincipal, java.awt.BorderLayout.CENTER);

        menuCarteira.setText("Carteira");
        menuCarteira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCarteiraMouseClicked(evt);
            }
        });
        menuCarteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCarteiraActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuCarteira);

        menuHistorico.setText("Histórico");
        menuHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHistoricoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuHistorico);

        menuCotacao.setText("Cotações");
        menuCotacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCotacaoMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCotacao);

        menuBrooker.setText("Home Brooker");
        menuBrooker.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
                menuBrookerMenuCanceled(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
            }
        });
        menuBrooker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBrookerMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuBrooker);

        jMenu1.setText("Sair");

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCarteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCarteiraActionPerformed

    }//GEN-LAST:event_menuCarteiraActionPerformed

    private void menuCarteiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCarteiraMouseClicked
        TelaCarteira ob = new TelaCarteira();
        jpnPrincipal.add(ob);
        ob.setVisible(true); 
    }//GEN-LAST:event_menuCarteiraMouseClicked

    private void menuHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHistoricoMouseClicked
        TelaHistorico ob = new TelaHistorico();
        jpnPrincipal.add(ob);
        ob.setVisible(true); 
    }//GEN-LAST:event_menuHistoricoMouseClicked

    private void menuCotacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCotacaoMouseClicked
      TelaCotacao ob = new TelaCotacao();
        jpnPrincipal.add(ob);
        ob.setVisible(true); 
    }//GEN-LAST:event_menuCotacaoMouseClicked

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed

    }//GEN-LAST:event_menuSairActionPerformed

    private void menuBrookerMenuCanceled(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuBrookerMenuCanceled
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBrookerMenuCanceled

    private void menuBrookerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBrookerMouseClicked
      TelaHomeBroker ob = new TelaHomeBroker();
        jpnPrincipal.add(ob);
        ob.setVisible(true); 
    }//GEN-LAST:event_menuBrookerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jpnPrincipal;
    private javax.swing.JMenu menuBrooker;
    private javax.swing.JMenu menuCarteira;
    private javax.swing.JMenu menuCotacao;
    private javax.swing.JMenu menuHistorico;
    private javax.swing.JMenuItem menuSair;
    // End of variables declaration//GEN-END:variables
}
